name: PHP Composer

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  sniff_74:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Cache Composer dependencies
      uses: actions/cache@v2
      with:
        path: /tmp/composer-cache
        key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}
        
    - uses: php-actions/composer@v6
      with:
          php_version: 7.4
    
    - name: Remove auth.json file
      run: composer cs
